Task_1_1_2
ELz0N1/OOP pull request #2
Opened 2024-09-16 19:29 UTC by ELz0N1

2024-09-17 14:47 UTC, Sharapov-Maksim requested changes
Хорошая работа, доделывайте. Мягкий дедлайн зачтён

2024-09-17 14:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/Blackjack.java
> +            return getInput();
Рекурсивный повтор не надёжен так как количество возможных повторов огранчено размером стека, а потом JVM упадёт с `StackOverflowException`

2024-09-17 14:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/Blackjack.java
> +        void openCard(Card card) {
Данный метод не только печатает карту, но и открывает её, при этом находится в классе `GameIO`. Стоит разнести логику игры и ввод/вывод

2024-09-17 14:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/Blackjack.java
> +        if (result == Result.DealerWon) {
А такое возможно, чтобы дилер сразу при раздаче карт выиграл?

2024-09-17 14:47 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/CardDeck.java
> +            throw new NoSuchElementException("deck is empty");
Уже исключения бросаете, здорово) Не забывайте добавлять информацию об исключениях в javadoc (с помощью `@throws`).

А ещё расскажите, что такое исключения и чем они полезны?

2024-09-22 13:03 UTC, ELz0N1 commented on Task_1_1_2/src/main/java/ru/nsu/Blackjack.java
> +        void openCard(Card card) {
Исправлено

2024-09-22 13:03 UTC, ELz0N1 commented on Task_1_1_2/src/main/java/ru/nsu/Blackjack.java
> +            return getInput();
Исправлено

2024-09-22 13:16 UTC, ELz0N1 commented on Task_1_1_2/src/main/java/ru/nsu/Blackjack.java
> +        if (result == Result.DealerWon) {
Нет. Пока дилер не вскроет карты, он не может выиграть. Исправлено

2024-09-22 13:16 UTC, ELz0N1 commented on Task_1_1_2/src/main/java/ru/nsu/CardDeck.java
> +            throw new NoSuchElementException("deck is empty");
Исключения это специальные объекты, которые сигнализируют о возникновении ошибок или необычных ситуаций во время выполнения программы. Они позоволяют программе обрабатывать их, предотвращая сбои программы. Исключения нужны для обеспечения надежности и структурирования кода

2024-09-24 05:20 UTC, Sharapov-Maksim requested changes
Замечания выданы на семинаре

2024-09-24 15:43 UTC, Sharapov-Maksim commented
Напишите какие были замечания

2024-09-24 16:02 UTC, ELz0N1 commented
Нужно было написать тесты для getInput, handleDealer и checkState

2024-09-24 16:26 UTC, Sharapov-Maksim approved these changes
Замечания исправлены, задание засчитано, PR можно мёржить
Жаль только вы не поправили все замечания checkstyle =(

2024-10-01 15:35 UTC, merged