Task_1_1_3
ELz0N1/OOP pull request #3
Opened 2024-10-03 16:11 UTC by ELz0N1

2024-10-03 17:11 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён (с учётом отсрочки), доделывайте требуемую функциональность

2024-10-03 17:11 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        return variables.getOrDefault(name, 0);
Если не нашлось переменной, то ситуация, можно сказать, исключительная. Лучше воспользоваться механизмом исключений, чем задавать дефолтное значени.

2024-10-07 18:24 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        return variables.getOrDefault(name, 0);
Исправлено

2024-10-08 04:53 UTC, Sharapov-Maksim requested changes

2024-10-08 04:53 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Expression.java
> +            int value = Integer.parseInt(parts[1].trim());
`Integer.parseInt` может выкинуть исключение, нужно поймать и сделать новое исключение с причиной и доп. информацией (например, `"Wrong value for variable " + variable`)

2024-10-08 04:53 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        }
А зачем создавать исключение и тут же его ловить? Нужно выбросить его, и пусть пользователь вашего кода сам решает, что с этим делать, вы такую ситуацию обработать не можете. И надо добавить информацию об исключении в javadoc `eval`. И `ValueErrorException` можно сделать unchecked (`extends RuntimeException`), тогда не придётся его прописывать в сигнатуру

Ваши классы для выражений, по сути, могут быть использованы в качестве библиотечных. И в том, чтобы печатать сообщение и выходить из программы есть минус: так вы отбираете у пользователя ваших классов контроль над исполнением программы и бескомпромиссно завершаете работу. К тому же протестировать такое поведение сложно

2024-10-08 04:53 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        System.err.println("Can't evaluate variable");
`"Can't evaluate variable" + name`

2024-10-08 04:53 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        System.exit(1);
Создать исключение вместо завершения работы программы

2024-10-08 04:53 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/ru/nsu/TestAdd.java
> +    }
Тут бы добавить тест на упрощение выражения без переменных

2024-10-08 04:53 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Add.java
> +    }
Я не уверен, что такая реализация сможет упростить выражение `(2 + (1 + (0 * x)))` до `3`, думаю вернётся `(2 + 1)`. Сделайте тест на это.
Если не заработает, то я бы добавил в конец проверку на то, можно ли вычислить новое выражение полностью, перед тем как создавать `Add(..., ...)`

2024-10-08 19:20 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Expression.java
> +            int value = Integer.parseInt(parts[1].trim());
Исправил

2024-10-08 19:21 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        }
Исправил

2024-10-08 19:21 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        System.err.println("Can't evaluate variable");
Исправил

2024-10-08 19:21 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Variable.java
> +        System.exit(1);
Исправил

2024-10-08 19:21 UTC, ELz0N1 commented on Task_1_1_3/src/test/java/ru/nsu/TestAdd.java
> +    }
Добавил

2024-10-08 19:21 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Add.java
> +    }
Исправил

2024-10-09 03:33 UTC, Sharapov-Maksim requested changes
Выдал новые замечания, про отсрочку помню

2024-10-09 03:33 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Add.java
> +            return new Add(newLeft, newRight).simplify();
Может лучше `new Number (newLeft.simplifyEval() + newRight.simplifyEval())`? А то новый Add создавать и упрощать как-то странно

2024-10-09 03:33 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Mul.java
> +    }
Здесь тоже нужно обработать случай, когда выражение можно вычислить целиком после упрощения левой и правой части. И, на самом деле, это можно проверять сразу после упрощения частей, чтобы `simplifyEval` вызывался только единожды для каждой части на любом пути исполнения.

Аналогичное замечание относится и к `Sub`, и к `Div`

2024-10-09 03:33 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/Mul.java
> +    }
И тесты на такие сценарии нужны для всех операций

2024-10-10 16:37 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Mul.java
> +    }
Исправлено

2024-10-10 16:37 UTC, ELz0N1 commented on Task_1_1_3/src/main/java/ru/nsu/Add.java
> +            return new Add(newLeft, newRight).simplify();
Исправлено

2024-10-10 17:23 UTC, Sharapov-Maksim approved these changes
Задание зачтено, доп. баллы: 2

PR можно мёржить

2024-10-11 23:03 UTC, merged