Task_1_2_1
ELz0N1/OOP pull request #4
Opened 2024-10-15 17:29 UTC by ELz0N1

2024-10-17 10:41 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн **не зачтён**, переделывайте самостоятельно

2024-10-17 10:41 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +public interface Graph {
У всех методов надо описать поведение в краевых случаях. Например, когда добавляемая вершина уже существует, или когда не существуют вершины добавляемого ребра и т.д.

2024-10-17 10:41 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/AdjacencyListGraph.java
> +                neighbors.remove(vertex);
Заметьте что `contains` принимает `Object`, а `remove` принимает `int index`. 
Предположу, что вы хотели так:
```
neighbors.remove((Integer) vertex);
```

2024-10-17 10:41 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/AdjacencyListGraph.java
> +                neighbors.remove(vertex);
Нужно сделать более сложные тесты, чтобы такие ситуации отлавливать

2024-10-17 10:42 UTC, Sharapov-Maksim commented
Копия решения https://github.com/NataliaResh/OOP/pull/10/files

2024-10-17 17:48 UTC, Sharapov-Maksim commented
> Копия решения https://github.com/NataliaResh/OOP/pull/10/files

По крайней мере `TopologicalSort` и `IncidenceMatrixGraph`

2024-12-14 09:00 UTC, Sharapov-Maksim requested changes

2024-12-14 09:00 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +public interface Graph {
> Не забудьте поддержать операции сравнения на равенство и вывода в строку.

Не хватает метода `equals`

2024-12-14 09:00 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/IncidenceMatrixGraph.java
> +        edges.add(new int[]{source, destination});
Ребро можно представить объектом, давайте для ребра сделаем класс

2024-12-14 09:00 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +public interface Graph {
Расскажите, как добавить в имеющуюся объектную модель новый способ представления графа?

2024-12-17 17:17 UTC, ELz0N1 commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +public interface Graph {
Добавил

2024-12-17 17:17 UTC, ELz0N1 commented on Task_1_2_1/src/main/java/ru/nsu/IncidenceMatrixGraph.java
> +        edges.add(new int[]{source, destination});
Сделал

2024-12-17 17:17 UTC, ELz0N1 commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +public interface Graph {
Нужно создать класс, реализующую объектную модель Graph, и определить методы интерфейса под новый способ представления графа

2024-12-18 15:15 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +    default boolean equals(Graph otherGraph) {
Лучше переопределите `Object.equals()`, и внутри проверьте, что `other` - граф

2024-12-18 15:15 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +        }
Так как порядок возращаемых вершин не специфицирован, то в общем случае такая проверка не работает.

Из описания `List.equals`:
> two lists are defined to be equal if they contain the same elements in the _**same order**_

Как вариант, можно преобразовать списки в множества. Или гарантировать отсортированность в `getGraphVertices`

2024-12-18 15:15 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +            }
Аналогично

2024-12-18 15:15 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +public interface Graph {
\* реализующий интерфейс Graph

2024-12-18 15:17 UTC, Sharapov-Maksim requested changes
Осталось `equals` поправить

2024-12-22 15:45 UTC, ELz0N1 commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +    default boolean equals(Graph otherGraph) {
Исправил

2024-12-22 15:45 UTC, ELz0N1 commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +        }
Исправил

2024-12-22 15:45 UTC, ELz0N1 commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +            }
Исправил

2024-12-22 17:04 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nsu/Graph.java
> +        }
Нужно было обновить javadoc к `getGraphVertices` тогда

2024-12-22 17:05 UTC, Sharapov-Maksim approved these changes
Задание зачтено

2024-12-22 18:55 UTC, merged