Task_1_2_2
ELz0N1/OOP pull request #5
Opened 2024-10-28 06:35 UTC by ELz0N1

2024-11-01 18:33 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён, доделывайте

2024-11-01 18:33 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +        }
Надо в javadoc описать поведение при `key == null`

2024-11-01 18:33 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +        }
Аналогично, про исключения нужно писать в javadoc

2024-11-01 18:33 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +            current.next = new Entry<>(key, value, null);
Протестировать

2024-11-01 18:33 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +    public boolean equals(Object obj) {
Из javadoc к Object.equals(), который вы переопределяете:

> It is generally necessary to override the hashCode method whenever this method is overridden, so as to maintain the general contract for the hashCode method, which states that equal objects must have equal hash codes.

Реализуйте `hashcode` тоже, с сохранением его контракта

2024-11-04 19:13 UTC, ELz0N1 commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +        }
Исправил

2024-11-04 19:13 UTC, ELz0N1 commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +        }
Исправил

2024-11-04 19:13 UTC, ELz0N1 commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +            current.next = new Entry<>(key, value, null);
Добавил тест

2024-11-04 19:15 UTC, ELz0N1 commented on Task_1_2_2/src/main/java/ru/nsu/HashTable.java
> +    public boolean equals(Object obj) {
Написал `hashCode` и тест к нему

2024-11-05 04:29 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-05 10:35 UTC, merged