Task_1_4_1
ELz0N1/OOP pull request #7
Opened 2024-11-25 17:02 UTC by ELz0N1

2024-11-25 18:24 UTC, Sharapov-Maksim requested changes
Замечания выданы

2024-11-25 18:24 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/StudentGradeBook.java
> +    }
> отсутствие оценок “удовлетворительно” за последние две экзаменационные сессии

Надо ещё чтобы эти две сессии вообще были пройдены, наверное

2024-11-25 18:24 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/StudentGradeBook.java
> +        List<CourseGrade> lastGrades = getGradesForLastSemester();
> 75% оценок в приложении к диплому (последняя оценка) – “отлично”;

Последнняя оценка имеется ввиду как последняя из тех что ставились за предмет, а не с последнего семестра

2024-11-25 18:24 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/Grade.java
> +    FAIL(2);
Не знаю, ставятся ли двойки в зачётку, но если добавили, то заиспользуйте в каком-нибудь тесте)

2024-11-25 18:24 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/StudentGradeBook.java
> +        }
А почему бы и нет?

2024-11-26 15:44 UTC, ELz0N1 commented on Task_1_4_1/src/main/java/ru/nsu/Grade.java
> +    FAIL(2);
Добавил

2024-11-26 15:44 UTC, ELz0N1 commented on Task_1_4_1/src/main/java/ru/nsu/StudentGradeBook.java
> +        List<CourseGrade> lastGrades = getGradesForLastSemester();
Исправил

2024-11-26 15:44 UTC, ELz0N1 commented on Task_1_4_1/src/main/java/ru/nsu/StudentGradeBook.java
> +    }
Исправил

2024-11-26 15:44 UTC, ELz0N1 commented on Task_1_4_1/src/main/java/ru/nsu/StudentGradeBook.java
> +        }
Исправил

2024-11-26 16:09 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-27 05:49 UTC, merged